### ISSUE TITLE
抖音 redirect_url 问题

### ISSUE THREAD

**Issue by CY-Christin** [hpyer/node-socialite#1]
hi，
我想问一下抖音获取用户信息的流程，下面是我的理解，如果有问题麻烦指出：
1. 先用 GET /platform/oauth/connect/ 获取 code
2. 用获取的的 code 使用 POST /oauth/access_token/ 获取 token
3. 使用 POST /oauth/userinfo/ 获取用户信息

现在想要在 3 获取到用户信息后跳转到一个页面中去，这个页面需要携带用户信息。但是 redirect_url 是在 1 中返回的，麻烦问下有什么好的解决方法吗？

**Comment by hpyer** [comment]
如果不考虑用户权限什么的，只是单纯把信息传给 redirect_url 对应的页面的话，可以考虑 localStorage 去暂存一下，回到页面后判断一下是否暂存了对应的数据就行

**Comment by CY-Christin** [comment]
> 如果不考虑用户权限什么的，只是单纯把信息传给 redirect_url 对应的页面的话，可以考虑 localStorage 去暂存一下，回到页面后判断一下是否暂存了对应的数据就行

我能否在 node 的一个接口中获取 code 通过 code 获取 token 再通过 token 获取用户信息，然后拼接到redirect_url上返回？

**Comment by CY-Christin** [comment]
已经解决了，协商后多加一个页面做redirect_url 然后从跳转的页面里获取信息。感谢您的帮助
